#' A method for plotting crmetric objects
#' 
#' Takes a df generated by RQ1 and plots the behavior of its metrics 
#' for the specified subsamples. 
#' 
#' @author Richard D. Yentes \email{rdyentes@ncsu.edu}
#' @param x a df generated by runnign rq1
#' @param min the minmum of the interval over which to evaluate the behavior 
#' @param max the maximum of the interval over which to evaluate the behavior

plotBehavior <- function(x, method, min=-3, max=3) {
  lsRQ1 <- function(df, ...) {
    ls <- dispatchRQ1(df, what='longstring', from=min, to=max, by=.1, i=i)
  }
  
  switch(method, 
         "lsRQ1" = lsRQ1(x, ...)
  )
}