#' A method for plotting crmetric objects
#' 
#' Takes a df generated by RQ1 and plots the behavior of its metrics 
#' for the specified subsamples. 
#' 
#' @author Richard D. Yentes \email{rdyentes@ncsu.edu}
#' @param x a df generated by runnign rq1
#' @param min the minmum of the interval over which to evaluate the behavior 
#' @param max the maximum of the interval over which to evaluate the behavior
#' @export

plotBehavior <- function(x, method, ...) {
  lsRQ1 <- function(df, ...) {
    args <- list(...)
    ls <- dispatchRQ1(df, what='longstring', from=args$min, to=args$max, by=.1, i=i)
    plot(ls$informedness, i)
  }
  
  switch(method, 
         "lsRQ1" = lsRQ1(x, ...)
  )
}